name: ebkit_app
description: "EbKit App"
version: 1.0.0
publish_to: none
resolution: workspace
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_boost:
    git:
        url: 'https://github.com/wyq0918dev/flutter_boost.git'
        ref: 'f3228638f68df7fd1caea3ffe733736e7cd7a365'
  cupertino_icons: ^1.0.8
  battery_plus: ^6.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: io.ebkit.flutter
